/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SearchData } from "./models/SearchData";
export namespace Components {
    interface IbeHotelSearch {
        "bgColor": string;
        "language": string;
        "propertyId": string;
        "textColor": string;
        "url": string;
    }
    interface IbeHotelSearchView {
        "bgColor": string;
        "propertyId": string;
        "textColor": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLIbeHotelSearchElement extends Components.IbeHotelSearch, HTMLStencilElement {
    }
    var HTMLIbeHotelSearchElement: {
        prototype: HTMLIbeHotelSearchElement;
        new (): HTMLIbeHotelSearchElement;
    };
    interface HTMLIbeHotelSearchViewElement extends Components.IbeHotelSearchView, HTMLStencilElement {
    }
    var HTMLIbeHotelSearchViewElement: {
        prototype: HTMLIbeHotelSearchViewElement;
        new (): HTMLIbeHotelSearchViewElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ibe-hotel-search": HTMLIbeHotelSearchElement;
        "ibe-hotel-search-view": HTMLIbeHotelSearchViewElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface IbeHotelSearch {
        "bgColor"?: string;
        "language"?: string;
        "propertyId"?: string;
        "textColor"?: string;
        "url"?: string;
    }
    interface IbeHotelSearchView {
        "bgColor"?: string;
        "onSearched"?: (event: CustomEvent<SearchData>) => void;
        "propertyId"?: string;
        "textColor"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ibe-hotel-search": IbeHotelSearch;
        "ibe-hotel-search-view": IbeHotelSearchView;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ibe-hotel-search": LocalJSX.IbeHotelSearch & JSXBase.HTMLAttributes<HTMLIbeHotelSearchElement>;
            "ibe-hotel-search-view": LocalJSX.IbeHotelSearchView & JSXBase.HTMLAttributes<HTMLIbeHotelSearchViewElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
